sudo: false
language: python
python:
  - '3.6'
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
install:
  - pip install -r requirements.txt
  - pip install -e .
before_script:
  - wget https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory &
  - sleep 2
env:
  - AWS_SECRET_ACCESS_KEY=mock AWS_ACCESS_KEY_ID=mock
script:
  - make test
  - make lint
jobs:
  include:
    - stage: deploy
      python: '3.6'
      deploy:
        provider: pypi
        user: lyft-pynamodb-attributes
        password:
          secure: "ADg9ORJDV6kPReBS4VnWTg9STZ35Zxpd8bJTEpXaydY1igt799B1vsbc/dwpGBmiJ/3Qotrqcp4QYGhYlkP42eSmN+WlbZfFrEGTI9pZ4TeKk+UxtxKB52ebGTobo+IB/rPVDJ9omSOcX3kwPX5KP0wwjnd1Q83BNsR3E5QCouW2QEyscXKk1wQpkdMMIlqYEa47x1dAV0aN8NXBO59Am1lOz2X1Wi7agoIMsHH1cUhROWpGca/A0mIjXYNHLvPU8A9THYFw/Jc1iDLCFO1Fxb3/eCD7KJsY3ThHTkS7enSMDz+3AcklryGwOs0epIaH4onQuGIDHNxSlNsZ/S0Iw9YD+ejQnV2aPSE1kpz/bbVF+w8ptNQgCGkE9dCt0gYlYlUC2aD35jgcQ2XTxm5sK0k7O+IWXPRjKj4riuQXOHNY3vKJmEnHbLequzrX4N8t06EeUMQyQJuXK5/6wZxGy9Y8SfMYlQlhuZmhcflBFS21UUb9AXMh6/PAFK0jJrh1MOIFsBHkQFUJv496tna7GIrjH21RjxRB3ds91GdAhbs7XNtIXWjz46Xr0euuMweQCj1trEE3YzX3xaO/PGMPp2nxVse6IHnqxbjV1WprTC5jtOHba/WVvwhvpeD7q97NAEk6sQUxSlfhJkqvFdSp5pYo7cFLpwrTazwldFryyYM="
        on:
          tags: true
          distributions: sdist
          repo: lyft/pynamodb-attributes
