sudo: false
language: python
python:
  - '3.6'
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
install:
  - pip install -r requirements.txt
  - pip install -e .
before_script:
  - wget https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory &
  - sleep 2
env:
  - AWS_SECRET_ACCESS_KEY=mock AWS_ACCESS_KEY_ID=mock
script:
  - make test
  - make lint
jobs:
  include:
    - stage: deploy
      python: '3.6'
      deploy:
        provider: pypi
        user: lyft-pynamodb-attributes
        password:
          secure: "RUc/R9gEghZdNyCHSRy+Okfc/gecw1aZJhSX7tK7rgOeXz0Ms19YmvGmC+K2Tg4Wu095AQM2AdPheLJd/QiBcsguj9+qX9OsN0z1hP+ya0MLXh3GhDckTIoyW11zSR630eJpdMMfamwH//yzGDTN1PTLGQubZeO4GnLXCJL+YKzA794s4w5c3vsbALayV5Osef5PLHnNJJjIPaCnsxnYgWCe3QeqVT5sL7azZzrzXyhtcUd9HThXH6foj+r/74k2srMUfQ6e8yjdhmxJz8GTvvFQmP9dCH6YdixYpamFYR5mmPGBLf90NyvLYzHDNbw2Gk0njXVVi2wpFH1YI3A+mjB17rgbVhZp9Hs4o/u8it1okgwewIBROdzd9VRxjQ/eMWSxgkxw6tZOf+IWpRih2TmGGPVwG9F05tLdNSnlTYQDizowzyOS7RjbB+mS7pe9h99jeM4pnsio7vnBZEoMYu0U8Axd12zWrefBJcNUjH9gywOZSmUerZo3MfYYT3kUPeMRitjgMn8m/V5umFpbOo80cKWnb69fa6xwad87G2gopPzbqPb1jqQ8JehJH5F00DOU0Q0wm+xcdfBxrU2JDTFiTjFkZrVgzll4H8xYRPCrREoqTw1UXb0xB/B/6cN0Tb/iy2nLKOw89NPQSQ6q6MtmlqLa5wgaE7mYEqLqurA="
        on:
          tags: true
          distributions: sdist
          repo: lyft/pynamodb-attributes
