sudo: false
language: python
python:
  - '3.6'
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
install:
  - pip install -r requirements.txt
  - pip install -e .
before_script:
  - wget https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory &
  - sleep 2
env:
  - AWS_SECRET_ACCESS_KEY=mock AWS_ACCESS_KEY_ID=mock
script:
  - make test
  - make lint
jobs:
  include:
    - stage: deploy
      python: '3.6'
      deploy:
        provider: pypi
        user: lyft-pynamodb-attributes
        password:
          secure: "VbTg3iGjB54XLcky1JOnphLW1TA44OLD4jl+RoG9M16tGbpvPNvyu4Ni9dRmWE5t8OZe4bu9eEHzph27r8kF+U1A2lVQiZx2FpE9Cx/QKxmGPP/a0O1N3/jP7At57iCQ7qRVVI1lan4fktlbNrim0AL5rZbWQRx0gVJSUqePS5MDPyrihvd5MyUBdWydqL8Eet3K/vZqKGssAhbPynDmgEy/wtkYTt3nplsm57P/GOl7UduZp/+bsd4XHqKfYJJzRqrzXaL1AFi1rDOFsfPh7dpZ5Qgidewvpaybjfl7PI3j5VtivX9KkxxchwR7r4Z2lDFAXgWQkDYZ6Axm16BO+UaAedCZoYNuhDt9gGeB6+5XNRV2otByatxZoiAhhuvIsDguVw6SfjTwAemANiEvNdxQ+rRJPH6oB2d8GuG3lfP+7kadr7LlodW2keWGLgF6c0LbkIBOXEcysmF/sH3rZCvfmypnU+lpArTwjUG8iLv/RT3ThY1AZeXUnWxqNof420ziLecrw28wQDzlW15gdaG3XPj2AZ6WyccJpg21IgDm7jPMsbmXxEFbdvgYAka57XbXDFiGUwQ8Y+IZaV1e3oNPIEyvYL7ts3rFP7lCYVVJY3Kp7mGktnpVaB919/DwRGR7Q999FTK52UoN1PdoPn0dDy+n5qQTFDVh7hRLwb0="
        on:
          tags: true
          distributions: sdist
          repo: lyft/pynamodb-attributes
