sudo: false
language: python
python:
  - '3.6'
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
install:
  - pip install -r requirements.txt
  - pip install -e .
before_script:
  - wget https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory &
  - sleep 2
env:
  - AWS_SECRET_ACCESS_KEY=mock AWS_ACCESS_KEY_ID=mock
script:
  - make test
  - make lint
jobs:
  include:
    - stage: deploy
      python: '3.6'
      deploy:
        provider: pypi
        user: lyft-pynamodb-attributes
        password:
          secure: "k/WziRKSHiFanZYsu9ayYqZ9eqQbvdot2iw8mb4e0G28ahu5H9fcRMTlIyqpUAFz66aE33pOHG3WL8lcAnaw6RatffLLqVSiW7UTLncnJ1Naxh/8CobEGw3/Gwe8wEZOTGj5QG2c9eEh1YM6Bb3xT0xnxexnHHag3vQoD8wFUfmx05+lJ8+6THDyP1ZpVFx+WFyCNyJfp6493Nkm3Ph5GA4kye/5PQgyq8wh8savxqesp51RN6uEbn+f50upCqMa+gSzrgeo3LFyEUeSos4hk+4rJOV2qpbyTFB7wdOmAX6hfa1nVAY7gIccM4VYfErtkbgGeQf1OM7CtD2iM2wQXAXda5FX/19NfjThg4ccnyP5ubBiaFtAtYw4E+A45yHtl4isjzJpm8Tp5XoRAQN+aBdABKlLPTqG0JE7jLzyOG+T6O7bgz6zWLkzrrrIo2IYD54+gE0SDYEl1OXf43yoq7/NHhGdk5AXsC5doF2qZMglLR89OVFyd5Tz5ORHczet/DGe/pys9b3svLHIeQJ+ZC9bgthNHDQN+13AbpuVDjNYP3wWYe9Oy1fMemZNJhtaD0tg2ZfZPLOnpwJ3kR7bD3As1fuHXuoL3hrIrfx+ZiYdZFUvQO8xKXbWQU/Mr7ld93k9BOi0dcKa3iSTFV7vhhOOXqOAOrTwJ5WIKdeuKeE="
        on:
          tags: true
          distributions: sdist
          repo: lyft/pynamodb-attributes
